# Generated by Django 3.2 on 2022-03-15 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10, verbose_name='teléfono')),
                ('direccion', models.CharField(max_length=254, verbose_name='dirección')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='ProductPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payments')),
            ],
            options={
                'verbose_name': 'Product Payment',
                'verbose_name_plural': 'Product Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payments',
            name='productos',
            field=models.ManyToManyField(related_name='productos', related_query_name='producto', through='payments.ProductPayments', to='products.Product', verbose_name='productos'),
        ),
    ]
